### ISSUE TITLE
Dao contract redeploy

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/dao#10]
on each chain, dao has the same address

- [x] arbitrum
- [x] ethereum
- [x] darwinia
- [x] crab
- [x] mantle
- [x] polygon
- [x] zkSync
- [ ]  bsc
- [x]  op
- [x]  base
- [ ]  scroll
- [ ]  polygon zkEVM
- [ ]  gnosis
- [ ]  linea
- [ ]  moonbeam
- [ ]  blast
- [ ] astar zkEVM

**Comment by hujw77** [comment]
TimeLock
```sh
Address: 0x000000000f681D85374225EdEeADC25560C1fb3F
Salt: 0xa4390aa887eb9fe9ed94283ed393bbfeb0b301e904fac48ba5d3c176f41851c1
```

**Comment by hujw77** [comment]
Safe
```
Address: 0x000000000B745C4c164372461877cC3C0319b6d4
Salt: 0x410baea291752109001def12044da59d6c152c3ac63b7abd986ecb812378fd5a
```

**Comment by hujw77** [comment]
Backing Safe Box
```
Address: 0x0000000000d2B6dB21aED6e5aCcbFeCbBA37b51C
Salt: 0x3c222fcee2e05aa444b4428a0c8234a9d4bbd54fc07c337f9e9eaac20442cec4
```

**Comment by hujw77** [comment]
Migrated to Sphinx safe multisig `0xD0a0899c5dc2FEb253D57Ab0b7c6d1b1Fcbbf824`
